// Package doormenu implements DOORS.MNU file parsing for tresbbs.
//
// TriBBS configured doors with a DOORS.MNU text file in the node directory.
// Format (verified against the TriBBS 5.01 manual and a real board file):
//
//	border-bg,border-fg,bg,fg              <- color header (line 1)
//	door-type,description,batch-file,security
//	...
//
// The caller selects a door by its ordinal position (1, 2, 3, ...) — there is
// no per-door hotkey letter in the file. The door-type is a single character
// naming which drop file(s) TriBBS generates before launching the door:
//
//	D  DOOR.SYS (GAP etc.)      S  SFDOORS.DAT (Spitfire)
//	P  PCBOARD.* (PCBoard)      T  TRIBBS.SYS  (TriBBS)
//	R  DORINFO#.DEF (RBBS)      W  CALLINFO.BBS (WildCat)
//	U  UTIDOOR.TXT (UTI/MegaMail)
//
// tresbbs reads the same file unmodified so a sysop's existing DOORS.MNU works
// as-is.
package doormenu

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/jasondostal/tresbbs/domain"
)

// DoorMenuEntry is one door line from DOORS.MNU.
type DoorMenuEntry struct {
	Ordinal     int    // 1-based menu position; how the caller selects the door
	DoorType    byte   // D/P/R/S/T/W/U — which drop file(s) to generate
	Description string // door name/description shown in the menu
	BatchFile   string // the door's batch file (run to launch it)
	Security    int    // minimum security level
}

// dropFormatForType maps a DOORS.MNU door-type character to the tresbbs
// DropFormat that selects which drop file the door receives.
func dropFormatForType(t byte) string {
	switch t {
	case 'R', 'r':
		return "DORINFO"
	case 'W', 'w':
		return "CALLINFO"
	case 'U', 'u':
		return "UTIDOOR"
	case 'T', 't':
		return "TRIBBS"
	case 'S', 's':
		return "SFDOORS"
	case 'P', 'p':
		return "PCBOARD" // not generated by tresbbs; DOOR.SYS is still written
	default: // 'D' and anything else: the always-written DOOR.SYS suffices
		return "DOORSYS"
	}
}

// hotKeyForOrdinal returns the key a caller presses for the nth door (1-based):
// digits 1-9, then A, B, C... for doors beyond nine.
func hotKeyForOrdinal(n int) byte {
	if n >= 1 && n <= 9 {
		return byte('0' + n)
	}
	return byte('A' + (n - 10))
}

// ParseDoorsMnu parses a DOORS.MNU file into its door entries, skipping the
// color header line. Malformed item lines are dropped, matching TriBBS's
// tolerant loader.
func ParseDoorsMnu(path string) ([]DoorMenuEntry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening DOORS.MNU: %w", err)
	}
	defer f.Close()

	var entries []DoorMenuEntry
	sc := bufio.NewScanner(f)
	haveHeader := false
	ordinal := 0

	for sc.Scan() {
		line := strings.TrimRight(sc.Text(), "\r\n")
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, ";") {
			continue
		}
		if !haveHeader {
			haveHeader = true // first non-blank line is the color header
			continue
		}
		if e, ok := parseDoorsMnuLine(line); ok {
			ordinal++
			e.Ordinal = ordinal
			entries = append(entries, e)
		}
	}
	if err := sc.Err(); err != nil {
		return nil, fmt.Errorf("reading DOORS.MNU: %w", err)
	}
	return entries, nil
}

// parseDoorsMnuLine parses "door-type,description,batch-file,security".
func parseDoorsMnuLine(line string) (DoorMenuEntry, bool) {
	f := strings.SplitN(line, ",", 4)
	if len(f) < 4 {
		return DoorMenuEntry{}, false
	}
	dtype := strings.TrimSpace(f[0])
	if dtype == "" {
		return DoorMenuEntry{}, false
	}
	var sec int
	fmt.Sscanf(strings.TrimSpace(f[3]), "%d", &sec)
	return DoorMenuEntry{
		DoorType:    dtype[0],
		Description: strings.TrimSpace(f[1]),
		BatchFile:   strings.TrimSpace(f[2]),
		Security:    sec,
	}, true
}

// GetMonthlyDoorsMnu returns the path to the current month's DOORS.MNU file.
// TriBBS supported monthly door rotations using the pattern DOORS.M%02d
// where %02d is the month number (01-12).
//
// For example, in July it looks for DOORS.M07, in December DOORS.M12.
// If no monthly file exists, falls back to the base DOORS.MNU.
func GetMonthlyDoorsMnu(baseDir string) string {
	month := time.Now().Month()
	monthlyFile := filepath.Join(baseDir, fmt.Sprintf("DOORS.M%02d", month))
	if _, err := os.Stat(monthlyFile); err == nil {
		return monthlyFile
	}
	return filepath.Join(baseDir, "DOORS.MNU")
}

// LoadDoorsFromMnu loads DOORS.MNU and converts each entry to a domain.Door.
// The door-type becomes the DropFormat, the batch file becomes the Command, and
// the ordinal becomes the selection HotKey (doors are chosen by number).
func LoadDoorsFromMnu(mnuPath string) ([]domain.Door, error) {
	entries, err := ParseDoorsMnu(mnuPath)
	if err != nil {
		return nil, err
	}
	var doors []domain.Door
	for _, e := range entries {
		doors = append(doors, domain.Door{
			Name:       e.Description,
			HotKey:     hotKeyForOrdinal(e.Ordinal),
			Command:    e.BatchFile,
			Security:   e.Security,
			DropFormat: dropFormatForType(e.DoorType),
		})
	}
	return doors, nil
}

// CreateSampleDoorsMnu writes a sample DOORS.MNU in the real TriBBS format.
func CreateSampleDoorsMnu(path string) error {
	content := `7,0,6,15
S,Global War,GLOBAL,10
U,MegaMail,MEGAMAIL,10
T,Legend of the Red Dragon,LORD,10
D,Tradewars 2002,TW2002,10
`
	return os.WriteFile(path, []byte(content), 0644)
}
