package legacy

import (
	"fmt"

	"github.com/jasondostal/tresbbs/domain"
)

// ── SYSDAT1.DAT — system configuration ──────────────────────────────────────
// Calibrated against a real 256-byte SYSDAT1.DAT generated by TRIMAN.EXE. The
// leading string fields (board name, sysop, first-call date, archive ext) are
// confirmed byte-for-byte against real data; the packed numeric config that
// follows (0x60+) is still being calibrated from sample files.
const (
	sysdat1RecordSize = 256

	offBoardName  = 0x00
	offSysopName  = 0x29
	offFirstCall  = 0x52
	offArchiveExt = 0x5B
	strFieldMax   = 41

	// Numeric config words (16-bit LE at odd offsets — structs are #pragma
	// pack(1)); offsets verified against the real SYSDAT1.DAT byte values.
	offMaxTimePerLogon  = 0x6D // =60 in defaults
	offSysopSecurity    = 0x6F // "Min Sysop Security Level" =100
	offNewUserSecurity  = 0x71 // =10
	offNewUserTimeLimit = 0x73 // =60
	offMaxNodes         = 0x7D // "Total Nodes" =1
)

// ParseSystemConfig reads SYSDAT1.DAT into a domain.Config. Returns the config,
// non-fatal warnings, and a fatal error only if the file can't be read.
func ParseSystemConfig(path string) (*domain.Config, []string, error) {
	recs, rem, err := ReadRecords(path, sysdat1RecordSize)
	if err != nil {
		return nil, nil, err
	}
	if len(recs) == 0 {
		return nil, nil, fmt.Errorf("no %d-byte record found (file is %d bytes)", sysdat1RecordSize, rem)
	}
	buf := recs[0]
	cfg := &domain.Config{
		BoardName:        CString(buf, offBoardName, strFieldMax),
		SysopName:        CString(buf, offSysopName, strFieldMax),
		BBSStartDate:     CString(buf, offFirstCall, 10),
		MaxTimePerLogon:  Int16(buf, offMaxTimePerLogon),
		SysopSecurity:    Int16(buf, offSysopSecurity),
		NewUserSecurity:  Int16(buf, offNewUserSecurity),
		NewUserTimeLimit: Int16(buf, offNewUserTimeLimit),
		MaxNodes:         Int16(buf, offMaxNodes),
	}
	return cfg, nil, nil
}

// USERS.DAT field offsets — CONFIRMED against a real 256-byte-record USERS.DAT
// generated by TRIMAN.EXE (two users with distinctive values decoded cleanly).
// Note the real order is name, password, city, phone, birthdate — the alias sits
// way out at 0xC8, NOT next to the name (an early printf-width guess had it at
// 0x1F, which is actually the password field).
const (
	userRecordSize  = 256
	offUserName     = 0x00 // char[31]
	offUserPassword = 0x1F // char[16], plaintext in the original
	offUserCity     = 0x2F // char[31] "City, State"
	offUserPhone    = 0x4E // char[13]
	offUserBirth    = 0x5B // char[9] MM/DD/YY
	offUserSecurity = 0x85 // int (both sample users = 10; see note)
	offUserAlias    = 0xC8 // char[31]
	minUserRecord   = 0xE7 // record must at least span through the alias field
)

// parseUserRecord extracts one USERS.DAT record's identity fields. The password
// is the original plaintext; the caller re-hashes it.
func parseUserRecord(buf []byte) domain.User {
	return domain.User{
		Name:          CString(buf, offUserName, 31),
		Alias:         CString(buf, offUserAlias, 31),
		Password:      CString(buf, offUserPassword, 16),
		City:          CString(buf, offUserCity, 31),
		Phone:         CString(buf, offUserPhone, 13),
		BirthDate:     CString(buf, offUserBirth, 9),
		SecurityLevel: Int16(buf, offUserSecurity),
	}
}

// detectUserRecordSize infers the fixed record length. USERS.DAT is a headerless
// record array, so the true size is the smallest length ≥ minUserRecord that
// divides the file evenly AND makes every record's name printable and security
// level sane. Returns 0 if nothing plausible is found.
func detectUserRecordSize(data []byte) int {
	for size := minUserRecord; size <= 1024 && size <= len(data); size++ {
		if len(data)%size != 0 {
			continue
		}
		valid := true
		for off := 0; off < len(data) && valid; off += size {
			rec := data[off : off+size]
			if !plausibleNameField(rec[offUserName:offUserName+31]) {
				valid = false
			}
			if sec := Int16(rec, offUserSecurity); sec < 0 || sec > 1000 {
				valid = false
			}
		}
		if valid {
			return size
		}
	}
	return 0
}

// plausibleNameField reports whether a fixed name field looks like a real
// NUL-padded name (printable up to the terminator) or an empty/deleted slot.
func plausibleNameField(f []byte) bool {
	for _, b := range f {
		if b == 0 {
			return true // rest is padding
		}
		if b < 0x20 || b > 0x7E {
			return false
		}
	}
	return true
}

// ParseUsers reads USERS.DAT. Because the record size isn't hard-confirmed yet,
// it auto-detects it and reports the size + a confidence note, rather than
// importing misaligned garbage.
func ParseUsers(path string) ([]domain.User, []string, error) {
	recs, _, err := ReadRecords(path, 1)
	if err != nil {
		return nil, nil, err
	}
	data := flatten(recs)
	size := detectUserRecordSize(data)
	if size == 0 {
		return nil, []string{fmt.Sprintf(
			"USERS.DAT (%d bytes): could not determine the record layout — skipped (need a known-good sample)", len(data))}, nil
	}
	var users []domain.User
	for off := 0; off < len(data); off += size {
		u := parseUserRecord(data[off : off+size])
		if u.Name == "" && u.Alias == "" {
			continue // deleted/empty slot
		}
		users = append(users, u)
	}
	warns := []string{fmt.Sprintf(
		"USERS.DAT: auto-detected %d-byte records (%d users); imported name/alias/password/city/phone/birthdate/security — stat counters pending layout confirmation",
		size, len(users))}
	return users, warns, nil
}

func flatten(recs [][]byte) []byte {
	var out []byte
	for _, r := range recs {
		out = append(out, r...)
	}
	return out
}

// ── MCONF.DAT — message conferences ──────────────────────────────────────────
// 256-byte records confirmed against real data; the conference name sits at
// 0x14 (preceded by numeric fields that are all-default/zero in the sample, so
// security/private/echo offsets aren't pinned yet).
const (
	confRecordSize = 256
	offConfName    = 0x14 // char[40]
)

func ParseConferences(path string) ([]domain.Conference, []string, error) {
	recs, rem, err := ReadRecords(path, confRecordSize)
	if err != nil {
		return nil, nil, err
	}
	var confs []domain.Conference
	for _, rec := range recs {
		name := CString(rec, offConfName, 40)
		if name == "" {
			continue
		}
		confs = append(confs, domain.Conference{Name: name})
	}
	var warns []string
	if rem != 0 {
		warns = append(warns, fmt.Sprintf("MCONF.DAT: %d trailing bytes not a whole record", rem))
	}
	warns = append(warns, fmt.Sprintf("MCONF.DAT: imported %d conference name(s); security/private/echo flags pending calibration", len(confs)))
	return confs, warns, nil
}

// ── FAREA.DAT — file areas ───────────────────────────────────────────────────
// 256-byte records confirmed against real data: area name at 0x07, path at 0x2F.
const (
	fareaRecordSize = 256
	offFareaName    = 0x06 // char[40] (area name/description)
	offFareaPath    = 0x2F // char[40] (download path)
)

func ParseFileAreas(path string) ([]domain.FileArea, []string, error) {
	recs, rem, err := ReadRecords(path, fareaRecordSize)
	if err != nil {
		return nil, nil, err
	}
	var areas []domain.FileArea
	for _, rec := range recs {
		name := CString(rec, offFareaName, 40)
		if name == "" {
			continue
		}
		areas = append(areas, domain.FileArea{
			Name: name,
			Path: CString(rec, offFareaPath, 40),
		})
	}
	var warns []string
	if rem != 0 {
		warns = append(warns, fmt.Sprintf("FAREA.DAT: %d trailing bytes not a whole record", rem))
	}
	warns = append(warns, fmt.Sprintf("FAREA.DAT: imported %d area(s) (name+path); security/sort/CD-ROM flags pending calibration", len(areas)))
	return areas, warns, nil
}

func fileSize(path string) (int, error) {
	recs, rem, err := ReadRecords(path, 1)
	if err != nil {
		return 0, err
	}
	return len(recs) + rem, nil
}
